spring:
  config:
    activate:
      on-profile: default
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        jdbc:
          batch_size: 400
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  batch:
    jdbc:
      initialize-schema: always

server:
  compression:
    enabled: true
    mime-types: application/json, image/gif, image/jpeg, image/png
    min-response-size: 1024
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

weather:
  api-url: "http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList"


song:
  song-detail:
    csv-path: csv/song/song-detail-data.csv
  calendar-song:
    csv-path: csv/song/calendar-song-data.csv

movie:
  base-url: "https://www.kobis.or.kr"
  rank-url: "/kobis/business/stat/boxs/findDailyBoxOfficeList.do"
  detail-url: "/kobis/business/mast/mvie/searchMovieDtl.do"


selenium:
  selenium-driver-name: "chromedriver"
  selenium-driver-path: "/Users/sanggyun/Downloads/chromedriver-mac-arm64/"
  selenium-headless-path: "/Users/sanggyun/Downloads/chrome-headless-shell-linux64/chrome-headless-shell"
  selenium-bigKinds-page: "https://www.bigkinds.or.kr/v2/news/index.do"
  selenium-joongang-page: "https://www.joongang.co.kr/sitemap/index/"
  isHeadless: true

---



spring:
  config:
    activate:
      on-profile: env
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        jdbc:
          batch_size: 400
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

server:
  compression:
    enabled: true
    mime-types: application/json, image/gif, image/jpeg, image/png
    min-response-size: 1024
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

weather:
  api-url: "http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList"


song:
  song-detail:
    csv-path: csv/song/song-detail-data.csv
  calendar-song:
    csv-path: csv/song/calendar-song-data.csv

movie:
  base-url: "https://www.kobis.or.kr"
  rank-url: "/kobis/business/stat/boxs/findDailyBoxOfficeList.do"
  detail-url: "/kobis/business/mast/mvie/searchMovieDtl.do"

selenium:
  selenium-driver-name: "chromedriver"
  selenium-driver-path: "/usr/local/bin/"
  selenium-headless-path: "/home/ec2-user/chrome-linux64/chrome"
  selenium-bigKinds-page: "https://www.bigkinds.or.kr/v2/news/index.do"
  selenium-joongang-page: "https://www.joongang.co.kr/sitemap/index/"
  isHeadless: true


