spring:
  config:
    activate:
      on-profile: default
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          batch_size: 400
        dialect: org.hibernate.dialect.MySQLDialect
      open-in-view: false

  batch:
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-request-size: 110MB
      max-file-size: 100MB

server:
  compression:
    enabled: true
    mime-types: application/json, image/gif, image/jpeg, image/png
    min-response-size: 1024


logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG


front:
  url: "http://localhost:3000"

---

spring:
  config:
    activate:
      on-profile: product
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          batch_size: 400
        dialect: org.hibernate.dialect.MySQLDialect
      open-in-view: false

  batch:
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-request-size: 110MB
      max-file-size: 100MB


server:
  compression:
    enabled: true
    mime-types: application/json, image/gif, image/jpeg, image/png
    min-response-size: 1024


logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

front:
  url: "http://localhost:3000"