
---
# 백엔드 로컬환경
spring:
  config:
    activate:
      on-profile: default
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        jdbc:
          batch_size: 400
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-request-size: 110MB
      max-file-size: 100MB
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/haeyum?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dec1209*
    driver-class-name: com.mysql.cj.jdbc.Driver

  file:
    filePath: /Users/sanggyun/Documents/GitHub/haeyum-server/src/main/resources/img/
    fileUrl: /image/
    fileFullUrl: http://localhost:8080/image/


jwt:
  secret: mklmkkmfklwemflkemflkwmflwmfewkmfwefwfwefewfwefefewfefwedsdsdsdsdsdsdsdsdsdsdsdsd
  access-token-expiration-millis: 7200000 # 2시간
  refresh-token-expiration-millis: 604800000 # 7일



management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG



server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: "*/*"
    min-response-size: 1024

weather:
  api-url: "http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList"
  service-key: 3otq7waQPf2bLUuNPqfjfYT8uJ%2BsLP6QCoFHakvCbXyLEckADY%2F8YAJCYVUQwgJCq8Hrve7ALouZI4oyKT8J5Q%3D%3D


song:
  song-detail:
    csv-path: csv/song/song-detail-data.csv
  calendar-song:
    csv-path: csv/song/calendar-song-data.csv

movie:
  base-url: "https://www.kobis.or.kr"
  rank-url: "/kobis/business/stat/boxs/findDailyBoxOfficeList.do"
  detail-url: "/kobis/business/mast/mvie/searchMovieDtl.do"

youtube:
  baseUrl: "https://www.googleapis.com/youtube/v3"
  api-key: AIzaSyC-ib4O351ZMixIyrf4_nZQYwquPFT6eJk

news:
  joongang-page: "https://www.joongang.co.kr/sitemap/index/"

kaKao:
  clientId: eeea6d87ff0261c7795936bbea225e5c
  nonce: haeyumAppPrivateSecretIdKey
  adminKey: 7c4792e6ad563a5a6afd3c040954a9c1
  sendRedirect: "http://localhost:3000/oauth/kakao/authorize/fallback?accessToken="
  kakaoAuthorizeUrl: "https://kauth.kakao.com/oauth/authorize"
  kakaoAuthorizeRedirectUrl: "http://localhost:8080/oauth/kakao/authorize/fallback"
  kakaoTokenUrl: "https://kauth.kakao.com/oauth/token"
  kakaoLogoutUrl: "https://kapi.kakao.com/v1/user/logout"




---


# ec2 로컬환경
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          batch_size: 400
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-request-size: 110MB
      max-file-size: 100MB
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/haeyum_test?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dec1209*
    driver-class-name: com.mysql.cj.jdbc.Driver

  file:
    filePath: /home/ec2-user/haeyum/image-test/
    fileUrl: /image/
    fileFullUrl: http://15.164.52.83:8081/image/


jwt:
  secret: mklmkkmfklwemflkemflkwmflwmfewkmfwefwfwefewfwefefewfefwedsdsdsdsdsdsdsdsdsdsdsdsd
  access-token-expiration-millis: 7200000 # 2시간
  refresh-token-expiration-millis: 604800000 # 7일



management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG



server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: "*/*"
    min-response-size: 1024
  port: 8081



weather:
  api-url: "http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList"
  service-key: 3otq7waQPf2bLUuNPqfjfYT8uJ%2BsLP6QCoFHakvCbXyLEckADY%2F8YAJCYVUQwgJCq8Hrve7ALouZI4oyKT8J5Q%3D%3D


song:
  song-detail:
    csv-path: csv/song/song-detail-data.csv
  calendar-song:
    csv-path: csv/song/calendar-song-data.csv

movie:
  base-url: "https://www.kobis.or.kr"
  rank-url: "/kobis/business/stat/boxs/findDailyBoxOfficeList.do"
  detail-url: "/kobis/business/mast/mvie/searchMovieDtl.do"

youtube:
  baseUrl: "https://www.googleapis.com/youtube/v3"
  api-key: AIzaSyC-ib4O351ZMixIyrf4_nZQYwquPFT6eJk

news:
  joongang-page: "https://www.joongang.co.kr/sitemap/index/"

kaKao:
  clientId: eeea6d87ff0261c7795936bbea225e5c
  nonce: haeyumAppPrivateSecretIdKey
  adminKey: 7c4792e6ad563a5a6afd3c040954a9c1
  sendRedirect: "http://localhost:3000/oauth/kakao/authorize/fallback?accessToken="
  kakaoAuthorizeUrl: "https://kauth.kakao.com/oauth/authorize"
  kakaoAuthorizeRedirectUrl: "http://15.164.52.83:8081/oauth/kakao/authorize/fallback"
  kakaoTokenUrl: "https://kauth.kakao.com/oauth/token"
  kakaoLogoutUrl: "https://kapi.kakao.com/v1/user/logout"




---


#ec2 product 환경
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          batch_size: 400
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-request-size: 110MB
      max-file-size: 100MB
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/haeyum?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dec1209*
    driver-class-name: com.mysql.cj.jdbc.Driver

  file:
    filePath: /home/ec2-user/haeyum/image/
    fileUrl: /image/
    fileFullUrl: https://api.haeyum.kr/image/


jwt:
  secret: mklmkkmfklwemflkemflkwmflwmfewkmfwefwfwefewfwefefewfefwedsdsdsdsdsdsdsdsdsdsdsdsd
  access-token-expiration-millis: 7200000 # 2시간
  refresh-token-expiration-millis: 604800000 # 7일



management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG



server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  compression:
    enabled: true
    mime-types: "*/*"
    min-response-size: 1024
  port: 8080




weather:
  api-url: "http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList"
  service-key: 3otq7waQPf2bLUuNPqfjfYT8uJ%2BsLP6QCoFHakvCbXyLEckADY%2F8YAJCYVUQwgJCq8Hrve7ALouZI4oyKT8J5Q%3D%3D


song:
  song-detail:
    csv-path: csv/song/song-detail-data.csv
  calendar-song:
    csv-path: csv/song/calendar-song-data.csv

movie:
  base-url: "https://www.kobis.or.kr"
  rank-url: "/kobis/business/stat/boxs/findDailyBoxOfficeList.do"
  detail-url: "/kobis/business/mast/mvie/searchMovieDtl.do"

youtube:
  baseUrl: "https://www.googleapis.com/youtube/v3"
  4api-key: AIzaSyC-ib4O351ZMixIyrf4_nZQYwquPFT6eJk

news:
  joongang-page: "https://www.joongang.co.kr/sitemap/index/"

kaKao:
  clientId: eeea6d87ff0261c7795936bbea225e5c
  nonce: haeyumAppPrivateSecretIdKey
  adminKey: 7c4792e6ad563a5a6afd3c040954a9c1
  sendRedirect: "https://www.haeyum.kr/oauth/kakao/authorize/fallback?accessToken="
  kakaoAuthorizeUrl: "https://kauth.kakao.com/oauth/authorize"
  kakaoAuthorizeRedirectUrl: "https://api.haeyum.kr/oauth/kakao/authorize/fallback"
  kakaoTokenUrl: "https://kauth.kakao.com/oauth/token"
  kakaoLogoutUrl: "https://kapi.kakao.com/v1/user/logout"



