name: personal deploy EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
<<<<<<< HEAD
        run: ./gradlew clean build -x test
=======
        run: ./gradlew clean build
>>>>>>> develop

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./haeyum.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          source: haeyum.jar
          target: /home/ec2-user/haeyum/update

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            rm /home/ec2-user/haeyum/haeyum.jar || true
            rm /home/ec2-user/haeyum/haeyum.jar
            mv /home/ec2-user/haeyum/update/haeyum.jar /home/ec2-user/haeyum
            cd /home/ec2-user/haeyum
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar haeyum.jar --spring.profiles.active=prod > ./app.log 2>&1 &
            rm -rf /home/ec2-user/haeyum/update
